name: CI
on:
  - push
  - pull_request
jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        name: Build
        with:
          command: build
          args: --release --all-features
      - uses: actions-rs/cargo@v1
        name: Test
        with:
          command: test
      - uses: actions-rs/cargo@v1
        name: Check formatting
        with:
          command: fmt
          args: -- --check
